version: 0.1
phases:
  install: 
    commands:
      - echo Installing source NPM dependencies...
      - cd spaceship-app-redux && npm install
  build:
    commands:
      - echo Build started on `date`
      - cd spaceship-app-redux && npm run build
  post_build:
    commands:
      - echo "$CODEBUILD_BUILD_SUCCEEDING"
      # if build succeeds copy the dist folder into the s3 bucket
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
            aws s3 cp "spaceship-app-redux/build" "s3://${S3_BUCKET}" "--recursive";
            echo "Build completed on date";
        fi
artifacts:
  files:
    - '**/*'
  discard-paths: yes